import React from 'react';
import Container from '../components/layout/Container';
import Footer from '../components/elements/Footer';
import NavBar from '../components/elements/NavBar';

const TermsOfUsePage: React.FC = () => {
  return (
    <div>
      <NavBar />
      <Container>
        <div className="page-content" style={{ padding: '40px 0', maxWidth: '800px', margin: '0 auto' }}>
          <h1 style={{ fontSize: '2rem', color: '#2c3e50', marginBottom: '20px' }}>Terms of Use</h1>
          <p>
            Last updated: July 21, 2025
          </p>
          <p>
            Please read these Terms of Use ("Terms", "Terms of Use") carefully before using the Random Letter Generator website (the "Service") operated by Random Letter Generator ("us", "we", or "our"). Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service.
          </p>
          <p>
            By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.
          </p>

          <h2 style={{ fontSize: '1.5rem', color: '#2c3e50', margin: '30px 0 15px' }}>Use of the Random Letter Generator</h2>
          <p>
            Our Random Letter Generator is provided as a free service for educational, creative, gaming, and other personal uses. You may use the letters generated by our service for various purposes including but not limited to:
          </p>
          <ul style={{ marginLeft: '20px', lineHeight: '1.6' }}>
            <li>Word games and puzzles</li>
            <li>Educational activities</li>
            <li>Creative writing prompts</li>
            <li>Art and design projects</li>
            <li>Personal entertainment</li>
          </ul>

          <h2 style={{ fontSize: '1.5rem', color: '#2c3e50', margin: '30px 0 15px' }}>Limitations on Use</h2>
          <p>
            While we encourage creative use of our random letter generator, you agree not to use the Service:
          </p>
          <ul style={{ marginLeft: '20px', lineHeight: '1.6' }}>
            <li>In any way that violates any applicable national or international law or regulation</li>
            <li>To generate content that is harmful, threatening, abusive, or otherwise objectionable</li>
            <li>To attempt to interfere with or disrupt the service or servers</li>
            <li>For automated or excessive usage that may negatively impact the service for other users</li>
            <li>For any commercial purpose without our prior written consent</li>
          </ul>

          <h2 style={{ fontSize: '1.5rem', color: '#2c3e50', margin: '30px 0 15px' }}>Intellectual Property</h2>
          <p>
            The Service and its original content, features, and functionality are and will remain the exclusive property of Random Letter Generator and its licensors. The Service is protected by copyright, trademark, and other laws. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of Random Letter Generator.
          </p>
          <p>
            While the specific random letters generated by our service are not subject to copyright protection, any unique arrangements, compilations, or creative works you create using these letters may be eligible for your own copyright protection, subject to applicable laws.
          </p>

          <h2 style={{ fontSize: '1.5rem', color: '#2c3e50', margin: '30px 0 15px' }}>Disclaimer</h2>
          <p>
            The random letters generated by our service are produced using algorithmic methods and are intended to be random within the parameters you select. We make no guarantees regarding the statistical randomness, uniqueness, or suitability of the generated letters for any specific purpose. Users should apply their own judgment when using generated content for any purpose.
          </p>

          <h2 style={{ fontSize: '1.5rem', color: '#2c3e50', margin: '30px 0 15px' }}>Links To Other Web Sites</h2>
          <p>
            Our Service may contain links to third-party web sites or services that are not owned or controlled by Random Letter Generator. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party web sites or services. You further acknowledge and agree that Random Letter Generator shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such web sites or services.
          </p>

          <h2 style={{ fontSize: '1.5rem', color: '#2c3e50', margin: '30px 0 15px' }}>Changes</h2>
          <p>
            We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.
          </p>

          <h2 style={{ fontSize: '1.5rem', color: '#2c3e50', margin: '30px 0 15px' }}>Contact Us</h2>
          <p>
            If you have any questions about these Terms or our Random Letter Generator service, please contact us.
          </p>
          <p>
            contact@randomlettergenerator.com
          </p>
        </div>
      </Container>
      <Footer />
    </div>
  );
};

export default TermsOfUsePage;